### ISSUE TITLE
Please make a binary release

### ISSUE THREAD

**Issue by kilves76** [dr-anoroc/rawccopy#6]
Please make a binary release to make this accessible to more people than the minority who are programmers and have VS installed.
If there is no .EXE it doesn't exist for more than 99.9% of people. It might be easy to forget this here inside Github but it's the reality.

**Comment by dr-anoroc** [comment]
This has been [raised before](https://github.com/dr-anoroc/rawccopy/issues/1) and actually there is a [fork](https://github.com/spectatorBH/rawccopy) out there that covers it. Will try to merge it in if I find the time.

**Comment by dr-anoroc** [comment]
Hey, I've merged spectator's fork into the main now.

**Comment by kilves76** [comment]
> Hey, I've merged spectator's fork into the main now.

Any chance you could make an actual binary release. Not a programmer you know. Compiling it is beyond me (and probably 99.9% people who'd have some use for it, though).
